name: E2E Tests

inputs:
  workspace:
    description: Workspace to run E2E in
    required: true

runs:
  using: 'composite'
  steps:
    - name: Define Playwright Version
      id: define-playwright-version
      run: |
        PLAYWRIGHT_VERSION=$(cat package-lock.json | jq -r ".packages[\"node_modules/@playwright\/test\"].version")
        echo "playwright-version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Playwright Browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{steps.setup.outputs.node-version}}-playwright-${{ steps.define-playwright-version.outputs.playwright-version }}-${{hashFiles('packages/blog/playwright.config.js')}}

    - name: Install Playwright with it's dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npm run e2e:install --workspace ${{inputs.workspace}}
      shell: bash

    - name: Install Playwright's dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npm run e2e:install-deps --workspace ${{inputs.workspace}}
      shell: bash

    - name: Run E2E
      run: npm run e2e --workspace ${{inputs.workspace}}
      shell: bash

    - name: Upload E2E Test Report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: packages/${{inputs.workspace}}/playwright-report/
        retention-days: 30
