name: Subs Savvy CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'packages/sofash/**'
      - 'packages/digital-garden/**'
      - 'packages/subs-savvy/docs/**'
      - '.github/workflows/sofash.yml'
      - '.github/workflows/digital-garden.yml'
      - 'biome.jsonc'
      - '.editorconfig'
      - '**/README.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        uses: ./.github/actions/setup

      - name: Lint
        run: npx biome ci .

  ts:
    name: TS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        uses: ./.github/actions/setup

      - name: TS
        run: npm run ts:check --workspace subs-savvy

  are-translations-sorted:
    name: Are Translations Sorted
    runs-on: ubuntu-latest
    needs:
      - ts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        uses: ./.github/actions/setup

      - name: Are Translations Sorted
        working-directory: packages/subs-savvy
        run: node scripts/are-translations-sorted.ts

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - ts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: npm run test:coverage --workspace subs-savvy

      - name: Upload Unit Test Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: packages/subs-savvy/coverage/
          retention-days: 30

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - ts
    outputs:
      bundle-cache-hit: ${{ steps.cache-bundle.outputs.cache-hit }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        id: setup
        uses: ./.github/actions/setup

      - name: Build App Bundle
        run: npm run build --workspace subs-savvy

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: packages/subs-savvy/dist
          retention-days: 30

  e2e:
    name: E2E
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        id: setup
        uses: ./.github/actions/setup

      - name: Run E2E Tests
        uses: ./.github/actions/e2e
        with:
          workspace: 'subs-savvy'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - lint
      - ts
      - are-translations-sorted
      - build
      - e2e
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master'
    concurrency:
      group: subs-savvv-deploy
      cancel-in-progress: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node & NPM
        id: setup
        uses: ./.github/actions/setup

      - name: Download App Bundle
        uses: actions/download-artifact@v4
        with:
          name: bundle
          path: packages/subs-savvy/dist

      - name: Deploy Bundle
        working-directory: packages/subs-savvy
        run: npm run deploy --workspace subs-savvy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
